### ISSUE TITLE
Connect with GSSAPI authetication

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.socks5#2]
Need tests for connecting with GSSAPI authetication.  See [RFC 1961](https://tools.ietf.org/html/rfc1961) which also references [RFC 2743](https://tools.ietf.org/html/rfc2743) and [RFC 2744](https://tools.ietf.org/html/rfc2744) to describe GSSAPI and how it's used for SOCKS5 connections.

**Comment by krismcqueen** [comment]
One of the afore mentioned RFCs is a C-bindings, so perhaps [RFC 2832](https://tools.ietf.org/html/rfc2853), the Java Bindings, is more relevant.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#180
