### ISSUE TITLE
Connect with username/password authetication

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.socks5#3]
In [RFC 1928](https://tools.ietf.org/html/rfc1928) the username/password authetication is optional, so this is a placeholder issue for possible implementation of tests with this style of authentication.  The use of username/password authentication for SOCKS5 connections is detailed in [RFC 1929](https://tools.ietf.org/html/rfc1929).

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#179
