### ISSUE TITLE
UDP Associate tests

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.socks5#6]
As per [RFC 1928](https://tools.ietf.org/html/rfc1928), one request clients can make is a UDP Associate request.  As a pre-requisite for these tests there needs to be UDP support in K3PO.  Once that work is complete, need a set of tests for UDP Associate along with negative tests as per the specification.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#176
