### ISSUE TITLE
fix how docker-kdc is used in the tests

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.socks5#7]
To do the GSS-API authentication, [docker-kdc](https://github.com/tillt/docker-kdc) is used.  I made some modifications to the project and checked them in to my fork of specification.socks5.  However, the better way would be to fork docker-kdc into kaazing (or k3po), make the modifications, commit the modifications to the kaazing fork, then pull in docker-kdc as a dependency when running integration tests for specification.socks5.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#175
